### ISSUE TITLE
Facebook SDK being added to project when not required

### ISSUE THREAD

**Issue by ian-sayles** [firebase/FirebaseUI-iOS#1035]
### Step 2: Describe your environment

  * Objective C or Swift: Swift
  * iOS version: 15
  * Firebase SDK version: 9.1
  * FirebaseUI version: 12.2.0
  * CocoaPods Version: SPM
  
### Step 3: Describe the problem:

Every time I add FirebaseUI-iOS to my project using the SPM the Facebook SDK is also added, when I don't use Facebook sign in so don't want the SDK adding to my project.

#### Steps to reproduce:

Package location: https://github.com/firebase/FirebaseUI-iOS

The package products I select are :
FirebaseEmailAuthUI
FirebaseGoogleAuthUI
FirebaseOAuthUI
  
#### Observed Results:

Facebook SDK 12.3.2 is added to Package Dependencies

**Comment by morganchen12** [comment]
Does this end up in your build target as well, or just the checked out sources?

**Comment by paulb777** [comment]
Those two files are the Firebase Auth implementation files that enable Firebase Auth to work with a Facebook authentication provider

**Comment by morganchen12** [comment]
Right, those files have Facebook in their name, but they're Firebase files, not Facebook files. It seems like the Facebook repo is being cloned by SPM, but Facebook's SDKs aren't actually being built into your app.

The reason Facebook is checked out by SPM is because it's listed as a dependency, though you might not use the Facebook auth provider.
