### ISSUE TITLE
FirebaseUI nil user on updateUI

### ISSUE THREAD

**Issue by NeilHarper** [firebase/FirebaseUI-iOS#109]
* Objective C or Swift: Swift
  * iOS version: 9.3.3
  * Firebase SDK version: 3
  * CocoaPods Version: 1.0.1

I have built the Swift uidemo and updated it to use Facebook authentication.   
It goes to Facebook to authorise me but when it returns to the demo app it shows no user credentials.

The updateUI method does get called after Facebook authentication, but the user is always nil and hence the UI does not get updated.

I have checked https://github.com/firebase/FirebaseUI-iOS/issues/83 and I do not have the "Is App Secret embedded in the client?" turned on.

The logs show nothing to indicate there was any problem with authentication.

**Comment by morganchen12** [comment]
This may just be a bug in the sample. If you take a look at `AuthViewController.swift`, the login providers on the `authUI` instance aren't set until `viewDidAppear`. When `application(openURL:options:)` is called the `authUI` instance doesn't properly handle the URL if the Auth VC hasn't been presented since the login providers don't exist yet.

```swift
let providers: [FIRAuthProviderUI] = [
  FIRGoogleAuthUI(clientID: kGoogleAppClientID)!,
  FIRFacebookAuthUI(appID: kFacebookAppID)!,
]
self.authUI?.signInProviders = providers
```

Try setting these in `application(didFinishLaunchingWithOptions:)` instead and see if it works.

**Comment by morganchen12** [comment]
Nevermind, that doesn't sound right. I'll take a closer look soon.

**Comment by yramanchuk** [comment]
@NeilHarper can you please checkout latest version of FirebaseUI-iOS (0.5.6-rc3) and confirm this issue?
I was able to log-in with Facebook Provider. 
Considering issue to be fixed.

**Comment by yramanchuk** [comment]
Closing (no answer from user)
