### ISSUE TITLE
gtm-session-fetcher issue with firebase version 10.0 SDK

### ISSUE THREAD

**Issue by ian-sayles** [firebase/FirebaseUI-iOS#1111]
* Objective C or Swift: Swift
  * iOS version: n/a
  * Firebase SDK version: 10.0
  * FirebaseUI version: 12.3
  * CocoaPods Version: n/a using Package Manager
  
When upgrading Firebase SDK from 9.6 I get the following issue:

'firebaseui-ios' is incompatible with 'firebase-ios-sdk' because 'firebase-ios-sdk' 10.0.0 depends on 'gtm-session-fetcher' 2.1.0..<3.0.0 and no versions of 'firebase-ios-sdk' match the requirement 10.0.1..<11.0.0.

'firebaseui-ios' >= 12.0.0 practically depends on 'gtm-session-fetcher' 1.4.0..<2.0.0 because 'firebaseui-ios' 12.2.0 depends on 'gtm-session-fetcher' 1.4.0..<2.0.0 and 'firebaseui-ios' 12.3.0 depends on 'gtm-session-fetcher' 1.4.0..<2.0.0.

'firebaseui-ios' {12.0.0..<12.2.0, 12.2.1..<12.3.0, 12.3.1..<13.0.0} practically depends on 'gtm-session-fetcher' 1.4.0..<2.0.0 because 'firebaseui-ios' 12.1.0 depends on 'gtm-session-fetcher' 1.4.0..<2.0.0 and 'firebaseui-ios' 12.1.1 depends on 'gtm-session-fetcher' 

Is this issue due to my setup or Firebaseui is not yet compatible with latest Firebase SDK?

**Comment by ArturoLee** [comment]
I'n getting the same issue pretty much. I've been trying ti reset cache and derived data but nothing has worked.

Xcode 14.0
error project: Failed to resolve dependencies Dependencies could not be resolved because root depends on 'firebase-ios-sdk' 10.0.0..<11.0.0 and root depends on 'firebaseui-ios' 12.3.0..<13.0.0.
'firebaseui-ios' is incompatible with 'firebase-ios-sdk' because 'firebase-ios-sdk' 10.0.0 depends on 'gtm-session-fetcher' 2.1.0..<3.0.0 and no versions of 'firebase-ios-sdk' match the requirement 10.0.1..<11.0.0.
'firebaseui-ios' >= 12.3.0 practically depends on 'gtm-session-fetcher' 1.4.0..<2.0.0 because 'firebaseui-ios' 12.3.0 depends on 'gtm-session-fetcher' 1.4.0..<2.0.0 and no versions of 'firebaseui-ios' match the requirement 12.3.1..<13.0.0.

**Comment by morganchen12** [comment]
I tagged a new release today, please upgrade to 12.3.1 and let me know if there are any issues.
