### ISSUE TITLE
SPM - Facebook SDK version range outdated (..<"16.0.0") 

### ISSUE THREAD

**Issue by j-gironda** [firebase/FirebaseUI-iOS#1183]
### Versions:  
* FirebaseUI version: `13.1.0` 
* Facebook SDK version: `16.Y.Z`
  
### Problem:
Although `13.1.0` version changelog claims to have added support for Facebook SDK 16, adding `firebaseui-ios` as a dependency with SPM is incompatible with `facebok-ios-sdk` `16.Y.Z` 

#### Steps to reproduce:

  1. Add `facebook/facebok-ios-sdk` package as a dependency with SPM, selecting version `16.Y.Z`
  2. Add `firebase/firebaseui-ios` package as a dependency with SPM, selecting version `13.1.0`
  
#### Observed Results: 

Error on dependencies resolution: 
```
Failed to resolve dependencies. 
Dependencies could not be resolved because root depends on 'firebaseui-ios' 13.1.0.
'firebaseui-ios' 13.1.0 cannot be used because 'firebaseui-ios' 13.1.0 depends on 'facebook-ios-sdk' 11.0.0..<16.0.0 and root depends on 'facebook-ios-sdk' 16.2.0.
```
  
#### Expected Results: 

Compatibility with `facebook/facebook-ios-sdk` `16.Y.Z`
  
#### Relevant Code:

Although the `Podfile` was updated to use SDK 16, the `Package.swift` file still sets the range as `"11.0.0"..<"16.0.0"`
```swift
  dependencies: [
    .package(
      name: "Facebook", 
      url: "https://github.com/facebook/facebook-ios-sdk.git",
      "11.0.0"..<"16.0.0"
    ),
```

**Comment by ArturoLee** [comment]
We should be using v17 to fix the upload issue.
https://github.com/facebook/facebook-ios-sdk/releases/tag/v17.0.0

**Comment by SnehaPriya0110** [comment]
The latest release 13.2.0 is letting the Facebook-ios-sdk's version upto 16.y.z but not 17.y.z. If I try to install Facebook-ios-sdk with the latest version 17.y.z, it's having the same issue "Failed to resolve dependencies". We need the Facebook SDK's version to be more than 17 since the privacy manifest files are available in the latest versions of Facebook SDK.

Package.swift has not updated for 17.y.z version, it still ranges between 11 to 16
   .package(
       name: "Facebook", 
       url: "https://github.com/facebook/facebook-ios-sdk.git",
       "11.0.0"..<"17.0.0"
     ),
     .package(
       name: "Firebase",

**Comment by morganchen12** [comment]
Should be fixed now.
