### ISSUE TITLE
Please update FBSDKLoginKit to 17.0

### ISSUE THREAD

**Issue by fangyuxi** [firebase/FirebaseUI-iOS#1204]
Please update FBSDKLoginKit to 17.0

**Comment by zjamshidi** [comment]
I also need to update Facebook SDK because of their bug fixes especially the one on Xcode 16

**Comment by fangyuxi** [comment]
@morganchen12 Hi, could help us?

**Comment by morganchen12** [comment]
I'll update it sometime this week.

**Comment by fangyuxi** [comment]
Thank you

Morgan Chen ***@***.***>于2024年11月12日 周二上午12:48写道：

**Comment by morganchen12** [comment]
I ran into some issues releasing the new fix since FBSDKLoginKit 17 depends on Swift 6. I'll update on Monday but in the meantime you can use the main branch directly if you need these changes now.

**Comment by zjamshidi** [comment]
@morganchen12 any update on releasing the fix?

**Comment by morganchen12** [comment]
@zjamshidi Updating the minimum Swift version for FirebaseUI in order to be able to adopt FBSDKLoginKit 17 would be a breaking change. If you're using CocoaPods, you can use the `:branch => "main"` specifier to use FBSDKLoginKit 17 immediately, but in the meantime I'd like to wait for upstream Firebase to make a breaking change before updating FirebaseUI.

**Comment by morganchen12** [comment]
This is fixed now.

**Comment by zjamshidi** [comment]
Thanks! Does it require Firebase `11.6.0`? I have a Flutter module in my project, and because of that, I couldn’t upgrade beyond `11.4.0`.

here is my pod:
  ```
pod 'Firebase/Database', '~> 11.4.0'
  pod 'Firebase/Messaging', '~> 11.4.0'
  pod 'FirebaseInstallations', '~> 11.4.0'
  pod 'Firebase/Auth', '11.4.0'
  pod 'Firebase/Performance', '~> 11.4.0'
  pod 'FirebaseAppCheck', '~> 11.4.0'
  pod 'Firebase/Analytics', '~> 11.4.0'
  pod 'Firebase/DynamicLinks', '~> 11.4.0'
  pod 'Firebase/Crashlytics', '~> 11.4.0'
  pod 'FirebaseFirestore', '11.4.0'
  pod 'Firebase/InAppMessaging', '~> 11.4.0'
  pod 'FBSDKLoginKit', '~> 17.4.0'
  pod 'FBSDKCoreKit', '~> 17.4.0'
  pod 'FirebaseUI/Auth', '~> 15.0.0'
  pod 'FirebaseUI/Email', '~> 15.0.0'
  pod 'FirebaseUI/Facebook', '~> 15.0.0'
  pod 'FirebaseUI/OAuth', '~> 15.0.0'
  pod 'FirebaseUI/Google', '~> 15.0.0'
```

now I'm getting the following errors
<img width="746" alt="Image" src="https://github.com/user-attachments/assets/0b28003f-a4f9-4ea9-9365-7d73b1e1f15b" />

**Comment by zjamshidi** [comment]
Thanks! Does it require Firebase 11.6.0? I have a Flutter module in my project, and because of that, I couldn’t upgrade beyond 11.4.0.
