### ISSUE TITLE
Firebase Obj-C crashing after using with swift demo

### ISSUE THREAD

**Issue by yramanchuk** [firebase/FirebaseUI-iOS#135]
Both demo apps (swift and objc) are using the same database.
Obj-c demo crashes when using together with swift demo app.
Problem is in `FirebaseTableViewDataSource.m`
method  ` - (id)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath` line ` [model setValuesForKeysWithDictionary:snap.value];`

steps to reproduce:

- 1.1. install objc demo
- 1.2. login user in objc demo
- 1.3. send message in chat
- 2.1 install swift demo app 
- 2.2 login in swift app
- 2.3 send message in swift app (app can crash, please check this)
- 3. open obj-c app and scroll to last message -> app crashes

**Comment by mcdonamp** [comment]
In Swift a message has three fields `uid`, `name`, and `text` (https://github.com/firebase/FirebaseUI-iOS/blob/master/samples/swift/uidemo/ChatViewController.swift#L221-L230). On Obj-C it is missing `uid` (https://github.com/firebase/FirebaseUI-iOS/blob/master/samples/objc/FirebaseUIChat/Samples/Chat/FIRChatMessage.h#L21-L22).

This will work on Swift because it's not required (fancy guard lets), but will crash Obj-C because the call to `setValuesForKeysWithDictionary:` expects those properties to exist.

Both apps should use a consistent data model, which will solve the problem (either add `uid` to Obj-C or remove it from Swift). Also, would have been caught (and ideally solved) if the apps functioned the same way (if they both populated the cell using the magic model coercion).

**Comment by morganchen12** [comment]
Swift uses `uid` specifically so that messages sent in the Swift demo are compatible with those sent in the [FirebaseUI Android sample app](https://github.com/firebase/FirebaseUI-Android/tree/master/app/src/main/java/com/firebase/uidemo).

**Comment by yramanchuk** [comment]
I have changed database structure of samples. Each app will have it's own child.

Another point here was: app should not crash. Even if user had created wrong data base scheme we can show warning, but not crash

**Comment by mcdonamp** [comment]
The magic coercion is probably not a good thing to show in the demo app. We should remove it and leave it undocumented, since it has the nice behavior of crashing the app with unknown (or misnamed) properties. Changing the app will make Obj-C consistent with Swift.

I disagree with changing the paths--all the sample apps should work on the same database at the same root, otherwise the ability for someone to demo both platforms interoperating (one of the main goals of Firebase) is significantly diminished.

**Comment by morganchen12** [comment]
>I disagree with changing the paths--all the sample apps should work on the same database at the same root, otherwise the ability for someone to demo both platforms interoperating (one of the main goals of Firebase) is significantly diminished.

👍 👍 👍 👍  cross-platform is one of our biggest goals imo

**Comment by yramanchuk** [comment]
it was done only for test purposes. and anyway it's better than crashing apps.
Developers are responsible to create their own database structure.

Closing this ticket and considering issue to be solved.
