### ISSUE TITLE
FIRPasswordRecoveryViewController not available in Pod files

### ISSUE THREAD

**Issue by yorgosg** [firebase/FirebaseUI-iOS#136]
I would like to show the password recovery view straight from my app. I would like to ask you if there is a way to do this. I only seem to have the FIRPasswordRecoveryViewController nib files within my Firebase pod folders, and I am guessing that I would need the header file too, right?

I am using Xcode 7.2, Cocoapods 1.0.0 and the following Firebase pods:

Using Firebase (3.5.2)
Using FirebaseAnalytics (3.3.1)
Using FirebaseAuth (3.0.4)
Using FirebaseDatabase (3.0.2)
Using FirebaseInstanceID (1.0.8)
Using FirebaseMessaging (1.1.1)
Using FirebaseUI (0.5.5)

**Comment by yramanchuk** [comment]
Hi yorgosg,

We are going to review your request.

In a meanwhile you can fix this and similar issues personally.
Please chose one of the follow ways.

**Approach A:**
You can create repo fork and add `FIRPasswordRecoveryViewController.h` to public framework headers.
In order to do this:

- open `FirebaseUI.xcworkspace`
- change target membership of `FIRPasswordRecoveryViewController.h` from `project` to `public`
- run `build.swift` (located in project root)
- update `FirebaseUI.podspec` so it will be using your local build of `FirebaseUIFrameworks.zip`

Later you can submit your changes in pull request and after review they become publically available.

**Approach B:**
OR you can use cocoapod sources.
In order to do this:

-  update your `Podfile`: replace `pod 'FirebaseUI'` with 
```
  pod 'FirebaseAuthUI', :git => "https://github.com/firebase/FirebaseUI-iOS.git"
  pod 'FirebaseDatabaseUI', :git => "https://github.com/firebase/FirebaseUI-iOS.git"
  pod 'FirebaseFacebookAuthUI', :git => "https://github.com/firebase/FirebaseUI-iOS.git"
  pod 'FirebaseGoogleAuthUI', :git => "https://github.com/firebase/FirebaseUI-iOS.git"
  pod 'FirebaseTwitterAuthUI', :git => "https://github.com/firebase/FirebaseUI-iOS.git"

```
- run `pod update`
- if needed update imports (should look like `#import FirebaseAuthUI/FIRPasswordRecoveryViewController.h>`)

After that you have integrated you project with cocoa pod sources. You can use internal sources and debug them. 
I guess this will save you lots of time.

And still you can contribute improvements of pod sources.

**Comment by yramanchuk** [comment]
We are not going to expose FIRPasswordRecoveryViewController in v1.0.0
@yorgosg, you can do your current customization.
However, if this feature will be requested by more  users we can consider reviewing it.
