### ISSUE TITLE
supporting iOS version

### ISSUE THREAD

**Issue by dakeshi** [firebase/FirebaseUI-iOS#171]
I think that we need to make clear about iOS version supporting issue again.
(related issue : #112, #113, related PRs: #170)

After 0.6.0, FirebaseUI supports iOS 8.0+.
I'm not sure that we need to mention `0.5` version which can support iOS 7.0.

And `FirebaseUI.podspec` use 7.0 for deployment_target but dev_podspec files support 8.0+.
I think that `FirebaseUI.podspec` needs to increase its version to 8.0.

**Comment by yorgosg** [comment]
Is iOS 7 no longer supported because of using Twitter login only?

**Comment by dakeshi** [comment]
@yorgosg, I think that there is more complicated reasons.

@mcdonamp mentioned this topic in #75 before:

>The root cause of all our CocoaPods issues is that we support iOS 7 (and thus, we ship static libs wrapped in Frameworks), while Apple (and CocoaPods by extension), really couldn't care less about supporting old OS's or framework developers. As further proof, I don't believe XCode 8 ships with iOS 7 support :)

Yes. he is right. Xcode 8 does not support iOS 7 deployment target anymore.
And dynamic framework support would be another reason, I think.

**Comment by morganchen12** [comment]
Our ability to adopt dynamic frameworks (which I would love to do) is limited by upstream Firebase only shipping static frameworks. It's unlikely that they'll change soon.

But yes, we should drop iOS 7 because TwitterKit (which we now have as a dependency) only supports iOS 8 and above, and we don't want to force external developers to keep multiple copies of Xcode around just to work on this codebase.

**Comment by morganchen12** [comment]
fixed in #176.
