### ISSUE TITLE
UITableViewCell Style Ignored

### ISSUE THREAD

**Issue by jtkendall** [firebase/FirebaseUI-iOS#18]
I've been trying to set a UITableViewCell's `detailTextLabel` but setting the style to anything other than Basic seems to have no effect even though the readme specifically states that it should be easily achieved. I'm using a standard UITableViewCell and everything else works, data is pulled from Firebase and appears in the `textLabel` without issue.

Am I doing something wrong? Did this get dropped without removing the reference from the readme?

```
self.datasource = FirebaseTableViewDataSource(ref: self.firebase, cellReuseIdentifier: "kProductCell", view: self.tableView)
self.datasource.populateCellWithBlock { (cell: UITableViewCell, obj: NSObject) -> Void in
	let snap = obj as! FDataSnapshot
	cell.textLabel?.text = snap.key as String
	cell.detailTextLabel?.text = "0"
}
self.tableView.dataSource = self.datasource
```

**Comment by jtkendall** [comment]
This was my fault, apparently last night my brain didn't register that `FirebaseTableViewDataSource()` had an initializer that has a `prototypeReuseIdentifier` param. Swapped `cellReuseIdentifier` out and my prototype cells started working fine.

**Comment by mcdonamp** [comment]
@jtkendall this is one of the unfortunate hiccups in trying to support the differences Apple presents between storyboards and regular xibs, sorry it cost you time (I wish there was a better answer for this issue than doing that)!

Also, `detailTextLabel` typically doesn't work in the standard version due to `UITableViewCellStyleDefault` not displaying it and my use of `dequeueCellWithReusableIdentifier` rather than programmatically creating a `UITableViewCell` with the desired cell style. This is on the list of fixes for a rewrite of the datasources to deal with sectioning (which will likely separate the view's attributes from the cells attributes more).

**Comment by coreywiley** [comment]
I'm having an issue getting the detailTextLabel to show up also:

        
        `dataSource = FireDataSource(ref: firebaseRef, cellReuseIdentifier: "UITableViewCell", view: tableView)
        tableView.dataSource = dataSource
        dataSource.populateCellWithBlock { (cell, obj) in
            let snap = obj as! FIRDataSnapshot
            
            if let newSong = Song(snapshot: snap) {
                cell.textLabel?.text = newSong.title
                cell.detailTextLabel?.text = newSong.artist
                //Print for verification
                print("textLabel: \(cell.textLabel?.text) detail: \(cell.detailTextLabel?.text)")
                print(newSong.artist)
            }
        }
    }`

Even though I'm assigning newSong.artist to cell.detailTextLabel.text it is printing out nil while everything else is working fine.
