### ISSUE TITLE
Editing an array loaded from FirebaseUI CollectionView

### ISSUE THREAD

**Issue by nhantrivinh** [firebase/FirebaseUI-iOS#209]
```swift
        var menus: [Menu] = [Menu]()

        self.collectionViewDataSource =
            FUICollectionViewDataSource(query: self.query!, view: self.collectionView, populateCell: {
                (view, indexPath, snapshot) -> UICollectionViewCell in

                let cell = view.dequeueReusableCell(withReuseIdentifier: Constants.Identifiers.Show.MenuCell, for: indexPath) as! MenuCell

                let menu = Menu(snapshot: snapshot)
                self.menus.append(menu)

                cell.configureCell(menu: menu)
                return cell
            })
        self.collectionView.dataSource = self.collectionViewDataSource
```

How do I edit the array with FirebaseUI CollectionView?
Say I added 5 arrays then deleted 1, how do I make my array update with FirebaseUI ?

**Comment by morganchen12** [comment]
FirebaseUI doesn't provide any extras for editing data in Firebase Database, which is why all of our data structures are readonly. You should consult the [FIRDatabaseReference](https://firebase.google.com/docs/reference/ios/firebasedatabase/api/reference/Classes/FIRDatabaseReference) documentation for how to write to Firebase Database.
