### ISSUE TITLE
Anonymous Auth

### ISSUE THREAD

**Issue by troy21688** [firebase/FirebaseUI-iOS#257]
I am trying to create a button that signs a user in anonymously to Firebase, receive a callback, and then if the sign in is successful transition to the next ViewController. Extremely new to programming so any help is appreciated:

   ```
    import UIKit
    import FirebaseAuth

     class ViewController: UIViewController {
    
    
    @IBAction func Auth(_ sender: Any) {
        FIRAuth.auth()?.signInAnonymously(completion: <#T##FIRAuthResultCallback?##FIRAuthResultCallback?##(FIRUser?, Error?) -> Void#>)

            //Receive callback showing completion or error, then navigate to next ViewController
    
    }
    

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
      }
    }`
`

**Comment by morganchen12** [comment]
Please post this issue over on the [StackOverflow](https://stackoverflow.com) forums and add the tags `firebase`, `firebaseui`, and `ios`/`swift`. It'll receive more appropriate attention there and the answer to your question will better serve as a reference for others in the future that have the same question.

Be aware that the StackOverflow community expects each question-asker to post what they have tried and what unexpected issue they ran into (otherwise your question may be closed without an answer).
