### ISSUE TITLE
Documentation on populating a Table

### ISSUE THREAD

**Issue by warhost** [firebase/FirebaseUI-iOS#264]
I was now searching for documentation for 2 hours, but I can't seem to find any.
The documentation on CocoaPods is outdated. Am I missing something here?

I am struggling with how to use these bindings, and was hoping for examples or documentation.

**Comment by morganchen12** [comment]
The most recent documentation is always going to be in the header comments in the source files. Is there anything you're looking for in particular?

That said, the docs haven't had the attention they should've since we shipped 1.0, mostly because I haven't gotten around to updating all of them. If you especially want one section updated, let me know.

Also, CocoaDocs is [going away soon](https://twitter.com/CocoaPods/status/841420312621154304). :(

**Comment by warhost** [comment]
Thanks for reply. Specifically I am looking for an example on how to use the tableview bindings. I had a functioning build earlier, updated my pods and the syntax and commands seemed to have changed a lot since then. The documentation I used earlier I can't find anymore, which is why I posted.

I am trying to populate a table from the database, I managed to get it compiling, but the table sadly remains empty.

**Comment by morganchen12** [comment]
Can you post your code here? It'll help me understand where our docs are most unclear and what use cases we should be serving.

**Comment by warhost** [comment]
To my understanding, it involves the `dataSource` being bound to a tableview, that part I have found in the documentation:

`self.dataSource = self.collectionView?.bind(to: self.firebaseRef) { collectionView, indexPath, snap in
  let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "reuseIdentifier", for: indexPath)
  /* populate cell */
  return cell
}`

However I am struggling with initializing a query to the `FUITableViewDataSource`. The following is what I had before updating this pod:

`
        dataSource = FirebaseTableViewDataSource.init(query: getQuery(),
                                                      prototypeReuseIdentifier: "Cellident",
                                                      view: self.tableView)
`
How does this translate into the current version using `FUITableViewDataSource`?

**Comment by morganchen12** [comment]
Ah, I see. We removed the observation of the query from the data source's initializer since it wasn't great to have the initializer have side effects (especially not side effects that could involve downloading a non-trivial amount of data). The basic flow is now this:

```swift
// First, create the data source that defines how firebase data will be mapped to
// the client UI.
self.dataSource = FUICollectionViewDataSource(query: getQuery()) { collectionView, indexPath, snap in
    let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "Identifier", for: indexPath)
    return cell
}

// Then, bind the data source to your UI element to receive data from the query.
self.dataSource.bind(to: self.collectionView)
```

In this case you'd just pass in your `getQuery()` to the data source initializer.

The `bind(query:populateView:)` method was added as a shorthand for this.

**Comment by morganchen12** [comment]
closing this issue, feel free to reopen if you've got more questions :)
