### ISSUE TITLE
Expose item snapshots in FUIIndexTableViewDataSource

### ISSUE THREAD

**Issue by ghowen** [firebase/FirebaseUI-iOS#282]
If a user selects a tableview cell from a table with a FUITableViewDataSource, I can access the complete data through the snapshotAtIndex method of the datas source, which is great.

With FUIIndexTableViewDataSource I only have access to the selected indexes though and have to load the data for the selected cell (again). Wouldn't it be great if there was also an array of snapshots of the actual data (like in the FUITableViewDataSource items)? The data has already been read anyways and passed to the populateCell parameter, so caching should be possible.

Thanks for looking into this!

**Comment by morganchen12** [comment]
Yeah, the contents are already stored in the indexed array and exposed as an array of items that have successfully loaded. This isn't that great though, since it means the indexes move around for items that haven't finished loading. We should add a `snapshot(atIndex:)` method that can return nil for snapshots that haven't finished loading yet.

Mind submitting a PR? If not, I'll probably try to make a PR for this by next week.

Thanks for filing!

**Comment by ghowen** [comment]
Great! I don't really know Objective-C, so a PR from my side is rather unlikely. But if you can give it a try, this would be fantastic. Any plans of porting FirebaseUI to Swift ;) ? 

Thanks again for looking into this!

**Comment by morganchen12** [comment]
This has been merged and will be a part of the next release.
