### ISSUE TITLE
Infinity activity indicator.

### ISSUE THREAD

**Issue by Tayphoon** [firebase/FirebaseUI-iOS#289]
Always sent same verification code and infinity activity indicator shown.

![screen shot 2017-06-02 at 14 56 40](https://cloud.githubusercontent.com/assets/1618506/26724876/45011548-47a4-11e7-9eac-324f61555147.png)

**Comment by morganchen12** [comment]
@Tayphoon can you upload a sample or post code that reproduces this issue?

**Comment by kovalskyy** [comment]
@morganchen12 @Tayphoon I have the same issue here. No matter valid/invalid code I enter it's stuck on activity indicator. Here is my code that call this controller: 

        //
        FUIAuth *auth = [FUIAuth defaultAuthUI];
        auth.delegate = self;
        //
        FUIPhoneAuth *phoneAuth = [[FUIPhoneAuth alloc] initWithAuthUI:auth];
        [phoneAuth signInWithPresentingViewController:self];

**Comment by yramanchuk** [comment]
@Tayphoon @kovalskyy There should be operation timeout and you should receive server error in:
`- (void)authUI:(FUIAuth *)authUI didSignInWithUser:(nullable FIRUser *)user error:(nullable NSError *)error`
Please wait for timeout (at least 2 min) and provide server error code (see instructions below).

In order to eliminate possible problems:
1. Remove app from device (we need to clean keychain), clean Xcode build folder
1. Verify that you enabled push notifications and remote notification in your app
1. Verify that you uploaded APNS certificate to FirebaseConsole
1. You can run app only on real device; 
1. Please comment out your app delegate APNS methods. Library swizzles and dynamically adds all needed calls to your code.
1. Provide here server error: from `authUI:didSignInWithUser:error:`
`NSError *detailedError = error.userInfo[NSUnderlyingErrorKey];
`
1. You can enable more detailed logs and provide them in this thread
- [ ] In `AppDelegate` add `#import <GTMSessionFetcher/GTMSessionFetcherLogging.h>`
- [ ] In `application:didFinishLaunchingWithOptions:` call `[GTMSessionFetcher setLoggingEnabled:YES];`
- [ ] Reproduce you case
- [ ] Download application container from device (in Xcode `Window -> Devices -> {YOUR_DEVICE} -> {YOUR_APP} -> Gear Icon -> Download Container`)
- [ ] Send us all logs from:
`Container.xcappdata -> AppData -> Documents -> GTMHTTPDebugLogs -> {YOUR_APP}`
8. Checkout sample app (in folder `samples`) and try to reproduce your issue there.

**Comment by kovalskyy** [comment]
I have resolved issue with this line of code when calling controller.
  auth.providers = @[phoneAuth];
When problem occurs once again I will adjust to your solution

**Comment by yramanchuk** [comment]
> I have resolved issue with this line of code when calling controller.

@kovalskyy Nice to hear!
@Tayphoon Can you please confirm that issue was fixed?

**Comment by Tayphoon** [comment]
@kovalskyy @yramanchuk Yes it's help.
