### ISSUE TITLE
What is passwordVerificationViewController for?

### ISSUE THREAD

**Issue by ryandailey100** [firebase/FirebaseUI-iOS#296]
I am having trouble understanding what passwordVerificationViewController does. What use does it have? Also how does that view controller get called?

**Comment by yramanchuk** [comment]
@ryandailey100 Good question 👍 
This controller used for `account linking`.
`Account linking` is triggered when you are using the same email for different providers (e g email provider and Google provider). With the help of this functionality we create only one account when your are using same email.

In your particular case here are steps to reproduce:
1. create Email account (sign in with email). Please use account different from gmail.
1. Sign out.
1. Sign in with Facebook/Twitter (account should have **the same email** as you were using in step 1).
1. Password verification controller is shown.

The idea behind this is to prove that you actually own email account and we can sign in with Facebook or Twitter. Otherwise someone can associate your email with his Facebook and use it to login in Firebase.

**Comment by ryandailey100** [comment]
Thanks! 👍
