### ISSUE TITLE
ReactiveCocoa Support

### ISSUE THREAD

**Issue by hsavit1** [firebase/FirebaseUI-iOS#3]
As an enhancement, this could be really neat to go along with Firebase

**Comment by mcdonamp** [comment]
Agreed with this, though the plan is to keep reactive extensions for Firebase in a separate repo and then incorporate them in as a dependency here where needed.

**Comment by hsavit1** [comment]
Agreed, they should probably be separate. 

Glad you guys are looking in the right direction! The combination of firebase + rac would be by far the fastest solution on the market

If you need a start, there's a (very small) Firebase+RACExtensions library going. I'll try to commit to it a bit more now that I know you guys are planning on using it :+1:

**Comment by mcdonamp** [comment]
Yep, I was going to reference it. The goal is to get RXJS, RXJava, and ReactiveCocoa bindings all under a single umbrella (similar to FirebaseUI) to get a common design paradigm across bot platforms.

We'll definitely take a look at the RACExtensions and see what we can learn :)

The main thing I've noticed (that I find a little interesting) is that it seems like the Reactive pattern is to have a single observable/signal that passes tagged events, rather than having multiple signals--very unlike our listeners (which are indeed just observables/signals depending on which language we're talking about), where we end up attaching multiple observers so we have typed observers. I'll put some more thought into it and see if we can get something out in all three.

We also need a good cross platform name (ReactiveFirebase, RXFirebase, RXFire, etc.) would all be on the appropriate vein ;)

**Comment by hsavit1** [comment]
Wow that seems ambitious! 

You're right in that it is a bit different from the standard reactive paradigm - you need to be able to push many events to only 1 subscriber. In the reactive pattern it is easy to push 1 event to many subscribers, but I'm not sure about the many to 1 thing. I think there could be some workarounds, however 

My vote is for RxFire

**Comment by mcdonamp** [comment]
I'll go ahead and close this for now, as it's being handled in separate repos.

**Comment by tunidev** [comment]
Any news about the progress and the integration with Firebase 3 ?

**Comment by mcdonamp** [comment]
For FirebaseUI or RX + Firebase?

**Comment by mfclarke** [comment]
There's some nice looking Swift extensions here, for ReactiveCocoa 4: https://github.com/guidomb/FirebaseFeed/blob/master/FirebaseFeed/Firebase%2BRAC.swift

@mcdonamp can you provide more info on the separate repos you mentioned when closing this issue? I can't find them but would like to contribute. Thanks!

**Comment by tunidev** [comment]
@mcdonamp I was asking about Firebase 3 + ReactiveCocoa 4 , but it seems that @mfclarke posted a useful link about that

**Comment by mcdonamp** [comment]
The best Swift + Firebase repo I know is here: https://github.com/RxSwiftCommunity/FirebaseRxSwiftExtensions

We've also got repos stubbed out ([rxfire-swift](https://github.com/firebase/rxfire-swift)), but haven't had time to upgrade everything yet.

**Comment by jakecraige** [comment]
Still very much a WIP, but I've been exploring wrapping the database layer with RxSwift and making it strongly typed by using Argo to parse out responses. 

Needs lots of work and is integrated into this project directly but might make a nice reference for folks, and if people find it interesting, at some point I can pull it out into it's own framework.

Main part of that here: https://github.com/jakecraige/Inventry/blob/master/Inventry/Models/Database.swift
