### ISSUE TITLE
Not able to get sms phone verification

### ISSUE THREAD

**Issue by kumararun540** [firebase/FirebaseUI-iOS#335]
### Step 2: Describe your environment

  * Objective C or Swift: ____Objective C
  * iOS version: _____10.3
  * Firebase SDK version: _____
  * FirebaseUI version: ____4.2.0
  * CocoaPods Version: ____
  
### Step 3: Describe the problem:
Error Domain=FIRAuthErrorDomain Code=17053 "There seems to be a problem with your project's Firebase phone number authentication set-up, please make sure to follow the instructions found at https://firebase.google.com/docs/auth/ios/phone-auth" UserInfo={NSLocalizedDescription=There seems to be a problem with your project's Firebase phone number authentication set-up, please make sure to follow the instructions found at https://firebase.google.com/docs/auth/ios/phone-auth, error_name=ERROR_MISSING_APP_TOKEN}

all steps followed as give in the doc- Sept up apns certificate etc. 

#### Steps to reproduce:

  1. _____In the enterphone screen 
  2. _____Select country code and select phone 
  3. _____getting alert something wrong. 
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by morganchen12** [comment]
Can you be more specific in your repro steps? What country are you selecting?

Please fill out the rest of the issue template.

**Comment by katowulf** [comment]
This doesn't demonstrate a bug in the FirebaseUI lib and looks like it's a problem with the SDK rather than this project. 

As the error message says, this is almost certainly a configuration issue. If you feel otherwise, you should [reach out to support](https://firebase.google.com/support/) or [file this in the iOS SDK repo](https://github.com/firebase/firebase-ios-sdk), but you will need to include a simplified and runnable example that reproduces the problem (which you haven't done here).

Some other troubleshooting ideas: Try an entirely new app using the quickstart code only (to isolate scope).

**Comment by vuppalasivakumar** [comment]
I am also facing the same issue can you guys how do u fixed.
