### ISSUE TITLE
Localization is not working for firebase UI

### ISSUE THREAD

**Issue by neerajpathak77** [firebase/FirebaseUI-iOS#354]
Localization for the Firebase phone UI is now working.
I am trying to pass the locale like below but it is having no effect

-(void) launchFireBasePhoneAuthUI {
    FUIAuth *auth = [FUIAuth defaultAuthUI];
    auth.delegate = self;
    FUIPhoneAuth *phoneAuth = [[FUIPhoneAuth alloc] initWithAuthUI:auth];
    auth.providers = @[phoneAuth];
    [FIRAuth auth].languageCode = @"he";
    [[FIRAuth auth] useAppLanguage];
    [phoneAuth signInWithPresentingViewController:self];
}

This is having no effect UI always takes the string which is on first index of preferredLocalizations
It always takes value of [NSBundle mainBundle].preferredLocalizations.firstObject.
So if my main bundle's first object is 'en' and I want to show the Firebase UI in Hebrew this is creating issues. May be because the exposed property 'languageCode' not taken care anywhere.
It takes the default value from 

+ (nullable FUIAuth *)authUIWithAuth:(FIRAuth *)auth {
  NSParameterAssert(auth != nil);
  @synchronized (self) {
    // Let the FIRAuth instance retain the FUIAuth instance.
    FUIAuth *authUI = objc_getAssociatedObject(auth, &kAuthAssociationKey);
    if (!authUI) {
      authUI = [[FUIAuth alloc] initWithAuth:auth];
      objc_setAssociatedObject(auth, &kAuthAssociationKey, authUI,
          OBJC_ASSOCIATION_RETAIN_NONATOMIC);
      if ([auth respondsToSelector:@selector(setAdditionalFrameworkMarker:)]) {
        auth.additionalFrameworkMarker = kFirebaseAuthUIFrameworkMarker;
      }
      // Update auth with the actual language used in the app.
      // If localization is not provided by developer, the first localization available,
      // ordered by the user's preferred order, is used.
      auth.languageCode = [NSBundle mainBundle].preferredLocalizations.firstObject;
    }
    return authUI;
  }
}

Assigning the property 'languageCode' making no effect :(

**Comment by morganchen12** [comment]
@yramanchuk what's the intended behavior here? Seems like we may have meant to make the property readonly.

FYI @neerajpathak77 if you hardcode the language code, it will break localization for all users except the ones whose language codes coincide with the one you're setting. If you want to test localizations, instead of setting the value in code you should set your device or simulator's language or locale through the Settings app.

**Comment by neerajpathak77** [comment]
@morganchen12 I think you are correct but here the thing is if a user wants app specific language I mean to say if we need a functionality to change language from inside the application than there is no way out. I think we can use 
[[[NSUserDefaults standardUserDefaults] objectForKey:@"AppleLanguages"] objectAtIndex:0]
rather than using  [NSBundle mainBundle].preferredLocalizations.firstObject. This will provide the flexibility to set app specific language.

**Comment by morganchen12** [comment]
Setting app-specific language is discouraged since system dialogues (share sheet/action sheet, SFSafariViewController, etc) will use the device locale/language and not the manually coded language, leading to a disjoint user experience where they suddenly have to switch languages inside the app.

This seems like a relatively easily supported feature, but @yramanchuk and @isaisachen should decide if this is something worth adding.

If it's not, though, that property should be marked readonly.

**Comment by morganchen12** [comment]
@neerajpathak77 we're not going to add this feature in the near future. I'll re-open this issue if the auth team reconsiders.
