### ISSUE TITLE
FUIBatchedArray: How to differentiate between initial data and subsequent updates?

### ISSUE THREAD

**Issue by ghowen** [firebase/FirebaseUI-iOS#359]
When I observe a query in FUIBatchedArray, the delegate's batchedArray:didUpdateWithDiff: is called when the array is initially filled with data and for each subsequent update.  

I would now like to know in the delegate if the array's inserts are the initial data or a subsequent update with an insert. 

Is there a way to track this state of the FUIBatchedArray? If not, this might be a nice feature to be implemented.

Thanks.

**Comment by morganchen12** [comment]
You can sort of do this currently by checking the [initial](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseFirestoreUI/FUISnapshotArrayDiff.h#L129) array in the diff information. If the array is empty, it's probably the initial update unless you've deleted everything in the collection and then re-inserted something.

What use case are you trying to accomplish?

**Comment by ghowen** [comment]
I was trying to implement pagination in a custom TableViewDataSource as I am working with large data sets (up to 10,000+ documents per collection) and I cannot afford (billing wise) for every user to read 1000+ records every time they open a table view. 

For this I was monitoring inserts, deletes etc. in FUIBatchedArray to reflect the changes in the respective queries of pages (each page had its own query). At the end I gave up though as I could not find a solution without more or less constantly rewriting queries for pages when the first or last element changed, and each rewrite of a query triggered a new series of costly reads... 

Any plans on supporting pagination for FirestoreUI (hopefully with a better algorithm) ?

**Comment by ghowen** [comment]
@morganchen12 But thanks for the hint with the initial array! I was briefly looking at the FUISnapshotArrayDiff class but was a bit overwhelmed by its magnitude ;)

**Comment by morganchen12** [comment]
Pagination doesn't work well with current FirestoreUI because it tries to keep every loaded item live-updating, which is not realistic for pagination of large sets. Ultimately we plan on enabling more simple scroll-to-refresh behavior (not necessarily pagination) by ditching the live-update constraint of all the already-loaded items, but it's unlikely that this lands before next year.

**Comment by ghowen** [comment]
Sounds great. I'll be looking forward to this. I refactored my paginated (or rather lazy loading) tableview datasource to use getDocuments instead of observing changes through FUIBatchedArray but this made the loading of the data feel "chunky" - there was nothing happening for a few secs and then the list filled "page by page". 

Then inspired by your last reply I refactored again using FUIBatchedArray, but after the first call to batchedArray:didUpdateWithDiff: I stop observing and work with the data statically. So far it works nice and smooth. The only caveat is that I have to manually do adds and deletes to the list as the user adds items to or deletes items from the list. But so far it seems to work fine.

**Comment by morganchen12** [comment]
Yeah, ultimately my implementation of this feature was going to be something like that--a FUIBatchedArray that instead of listening to live updates would only request updates any time the user interacted with an item, producing failure cases for items that no longer existed or were renamed or something (and certain actions like moves could be ignored). This is a lot like how modern social media apps handle feeds--if a post is deleted, it doesn't live update in the feed, clicking on it just takes the user to a page that says "this post no longer exists" or similar.

If you're feeling confident in your implementation, I'm happy to review a PR :)
