### ISSUE TITLE
Swift UITableView with Custom Subclasses of UI*ViewCell

### ISSUE THREAD

**Issue by kin4n** [firebase/FirebaseUI-iOS#40]
hello
Where is the prototypereuseidentifier ? I can see identifier in my cell (added to a tableview), but I can t seem to find online any information about a prototypereuseindetifier, is it the same thing ?

**Comment by mcdonamp** [comment]
If you're using prototype cells (in storyboards), you're going to use the constructor with `prototypeReuseIdentifier`, otherwise, if you would have otherwise used a call to `UITable/CollectionView registerClass: forCellWithReuseIdentifier` you should use cellReuseIdentifier. #16 has a long discussion on this as well.

For more information, check out [this helpful post](http://code.tutsplus.com/tutorials/ios-sdk-crafting-custom-uitableview-cells--mobile-15702) on working with UITableViews which can explain when to use either.
