### ISSUE TITLE
Extend bind to for fan outs

### ISSUE THREAD

**Issue by mickeysox** [firebase/FirebaseUI-iOS#422]
I am writing a chat app with the following fan out - user1 chatting to user2

Messages
——user 1
——-m1
———message: test

User-messages
—-user1
——m1
—-user2
——m1

To source the messages I get the user-message ids per user and then source the actual message.  However I don’t think this can be done when binding to the collection view because it only takes one reference.

I have tried various different ways to achieve this but they all feel very hacky.

**Comment by morganchen12** [comment]
Are you using Firestore or RTDB?

**Comment by mickeysox** [comment]
Hi,

RTDB.  Maybe my design is wrong.  I was trying to follow David East’s recommendation -and it seems reasonable to me.

Thanks

**Comment by morganchen12** [comment]
This is something you could do with [`FUIIndexCollectionViewDataSource`](https://github.com/firebase/FirebaseUI-iOS/blob/master/FirebaseDatabaseUI/FUIIndexCollectionViewDataSource.h), but your database structure would have to have all messages in a flat collection instead of nesting them under user IDs.

**Comment by morganchen12** [comment]
Closing since we won't add this feature to FirebaseUI, but feel free to continue discussion here if you'd like more assistance.
