### ISSUE TITLE
Pod Error Transitive Dependencies

### ISSUE THREAD

**Issue by richardreyes** [firebase/FirebaseUI-iOS#46]
Hi,

I am trying to build FirebaseUI-iOS-master/examples/FirebaseUIChat  when I ran pod install here's what I got:

`[!] The 'Pods' target has transitive dependencies that include static binaries: (/Users/richardgreyes/Downloads/FirebaseUI-iOS-master/examples/FirebaseUIChat/Pods/Google/Libraries/libGGLCore.a and /Users/richardgreyes/Downloads/FirebaseUI-iOS-master/examples/FirebaseUIChat/Pods/Google/Libraries/libGGLSignIn.a)`

How can I fix this?

Thanks

**Comment by jacoplane** [comment]
Having the same issue. I'm not trying the run the chat sample, but simply trying to install FirebaseUI to my existing project.

**Comment by davideast** [comment]
This is likely because you're using `use_frameworks!` with the Auth pod included. The current Google Auth pod, doesn't work with `use_frameworks!`.

If you're just looking for UI bindings use: `pod FirebaseUI/Core`

Or if you need to use the Auth pod, just remove `use_frameworks!`. 

I'm closing this issue, but give me a holler if it's still broken after these suggestions.
