### ISSUE TITLE
Problem translating firebase UI in iOS swift project

### ISSUE THREAD

**Issue by nole87** [firebase/FirebaseUI-iOS#462]
I have:

`authUI?.customStringsBundle = Bundle.main`

And FirebaseAuthUI.strings in my swift project and I need to translate firebase auth UI for iOS so I can realese my project but only few strings in app are translated other not. Where is the problem? Off course I translate it all!

**Comment by nole87** [comment]
I resolve all, only cancel button item in top left I can't translate!

**Comment by morganchen12** [comment]
The cancel button isn't a string provided by FirebaseUI; it's just a system cancel button. The same should be true for all other cancel buttons in your app.

**Comment by nole87** [comment]
I know that but I must translate it, I must find the way for it. I already lose one day :)

**Comment by morganchen12** [comment]
Since this is a string in a system button, I'm going to close this as it's not a FirebaseUI issue.

Keep in mind system buttons will use whatever localization language defined in the device's settings. If you want to override this, you'll have to customize the entire button since you don't have control over the string loading.
