### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by hsavit1** [firebase/FirebaseUI-iOS#5]
Im getting an error on line 28 of ViewController.m in the example project

    [self.dataSource populateCellWithBlock:^void(MessageTableViewCell * __nonnull cell, Message * __nonnull message) {

the error reads: "incompatible block pointer types sending 'void(^)MessageTableViewCell *__nonnull__strong, Message*__nonnull__strong)' to parameter of type 'void(^ __nonnull)(UITableViewCell *__nonnull__strong, NSObject *__nonnull__strong)'

**Comment by mcdonamp** [comment]
Looks like the problem is due to the fact that `__kindof` was introduced in Xcode 7 Beta 5 (and has essentially zero documentation), which means that this feature is really exclusively Xcode 7 b5 and above. I'll go ahead and fix the macros to use `id` instead of `__kindOf UITableViewCell *` which should solve this problem for now.

**Comment by hsavit1** [comment]
youre totally right about that. Im running xcode 6.4 so this makes plenty of sensee

**Comment by mcdonamp** [comment]
Should be in master as of: https://github.com/firebase/FirebaseUI-iOS/commit/264f596f610c85856e808fea370633c006f0a187

Since it's not pushed to Cocoapods, you'll need to do:
    pod 'FirebaseUI', :path => '../../'

Which will pull the pod in from the local git repo. Thanks for checking this!

**Comment by hsavit1** [comment]
got it to work, thanks !
