### ISSUE TITLE
Autoupgrade results in empty providerData

### ISSUE THREAD

**Issue by lswang1618** [firebase/FirebaseUI-iOS#504]
iOS version: 11.4
Firebase SDK version: FirebaseCore 5.5.0
FirebaseUI version: 5.2.0
CocoaPods Version: 1.5.3

### Step 3: Describe the problem:
When FUIAuth.defaultAuthUI()?.shouldAutoUpgradeAnonymousUsers = true, calling Auth.auth().currentUser?.providerData[0] from func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, error: Error?) results in a nil value.

So the display name and photoURL are not reachable. If the anonymous users bit is set to false, then providerData is no longer empty and works as expected.

#### Steps to reproduce:

  1. set FUIAuth.defaultAuthUI()?.shouldAutoUpgradeAnonymousUsers = true
  2. call Auth.auth().currentUser?.providerData[0] from func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, error: Error?)
  3. Sign in using a provider from the firebase UI picker
  4. Observe that providerData is an empty array. 
  
#### Observed Results:

 providerData is an empty array []
  
#### Expected Results:

providerData should have length 1 with the login information after signing in with a firebase UI login provider.

**Comment by morganchen12** [comment]
I won't have time to look at it this week, but will try to address this next week.

**Comment by lswang1618** [comment]
Okay thanks!

**Comment by morganchen12** [comment]
After combing through the code, I'm not entirely sure if this is a bug in FirebaseUI (don't worry though, we can still push fix for it upstream). Does refreshing the user correctly populate the `providerData` dictionary?

**Comment by lswang1618** [comment]
Debugged a little more, so if the authUI.shouldAutoUpgradeAnonymousUsers = false, the user is signed in through the provider and providerData is set, but if authUI.shouldAutoUpgradeAnonymousUsers = true, then the user is still an anonymous user even after logging in through a provider.

**Comment by lswang1618** [comment]
authDataResult is nil in func authUI also

**Comment by morganchen12** [comment]
Looking at the project, it looks like it's missing several files (fonts/images) and doesn't build off of a clone. I can replace these with placeholders for now.

**Comment by lswang1618** [comment]
Ah, sorry, I've mostly been working locally so didn't sync every file. But let me know if I can help with anything.

**Comment by victor-sarda** [comment]
Hi, I'm having the same issues here.

When I enable `shouldAutoUpgradeAnonymousUsers` it does convert the anonymous user to a permanent user **if it did not exist** but won't call the `func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, error: Error?)` auth delegate method.

Also, when I try to sign in still with `shouldAutoUpgradeAnonymousUsers` enabled from an anonymous user to an existing user, it does call the delegate method and I'm catching the `mergeConflict` error. This is what I expect to happen but I also expect authDataResult to not be `nil`, otherwise how am I supposed to sign in the existing user?

Let me now if I can help with anything 👍

**Comment by codemodouk** [comment]
I'm seeing the same issues described above. Additionally, when I have `shouldAutoUpgradeAnonymousUsers = true` and sign up a user that didn't previously exist, the Identifier on the Firebase Console Authentication page doesn't get updated with the user's email id. However, if I search for the email id, I can locate the user that was created. See image.

<img width="483" alt="screen shot 2018-09-05 at 21 53 01" src="https://user-images.githubusercontent.com/17314445/45120484-26bca080-b156-11e8-84b5-8a511807372d.png">

**Comment by morganchen12** [comment]
#512 partially fixes this issue, the fix to the behavior @victor-sarda describes is in #519.

**Comment by lswang1618** [comment]
Thanks for the update! Does #512 also populate authDataResult even if there's a mergeConflict error?

**Comment by morganchen12** [comment]
No. The docs around this are _exceedingly_ poor, but the merge conflict error basically means the two accounts can't be properly joined, since they both have their own separate account state that can't be resolved cleanly. In the case where this error arises, you should take the auth credential out of the `userInfo` dictionary of the error and [use it to sign in](https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes/FIRAuth#/c:objc(cs)FIRAuth(im)signInAndRetrieveDataWithCredential:completion:), discarding the state of the anonymous user in favor of the user that your app user is trying to login as.

**Comment by morganchen12** [comment]
I'll submit a PR for the docs shortly.

**Comment by codemodouk** [comment]
Hi, I've merged #519 into my project and when I attempt to sign in an existing user from an anonymous user the delegate method isn't being called. However, the delegate method is called when I sign up a new user from an anonymous account.

**Comment by morganchen12** [comment]
The fix has been released in 5.2.1.
