### ISSUE TITLE
no such module 'FirebaseUI'

### ISSUE THREAD

**Issue by mungra** [firebase/FirebaseUI-iOS#53]
Hi,

I'm trying to add FirebaseUI.framework into my project i downloaded from the release page using Swift

Xcode version : 7.3

### Steps to reproduce
  1. Downloaded FirebaseUI.framework from https://github.com/firebase/FirebaseUI-iOS/releases
  2. Dragged FirebaseUI.framework into my project
  3.  import FirebaseUI <---- gives error

See screenshot

![screen shot 2016-03-25 at 1 12 45 pm](https://cloud.githubusercontent.com/assets/4529053/14048188/6f4156c0-f28b-11e5-8c7c-b507e45cc545.png)

Thanks!

**Comment by craigpearce5** [comment]
I find this is a common issue with libraries managed through cocoapods.  Simply build your application (cmd - b) and it should resolve the issue.

**Comment by mcdonamp** [comment]
I think the problem is that you need a bridging header in Swift if you're including the framework directly.

```
#import <FirebaseUI/FirebaseUI.h>
```

This is probably because we're not creating a Clang module (no modulemap file in our framework), so you have to do the import for it to be visible.

Let me know if this works, and I can change the framework around to build a module. Or just try out CocoaPods and see if that solves the problems (it should, since CocoaPods builds the module).
