### ISSUE TITLE
Cannot build app for distribution due to FirebaseDatabaseUI not being bitcode compatible 

### ISSUE THREAD

**Issue by toddlee** [firebase/FirebaseUI-iOS#61]
When trying to build for app submission, I get this error and can't build for release.

> ld: bitcode bundle could not be generated because '/Users/todd/Development/projects/Mmm/Pods/FirebaseUI/FirebaseUIFrameworks/Database/Frameworks/FirebaseDatabaseUI.framework/FirebaseDatabaseUI(FirebaseCollectionViewDataSource.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mcdonamp** [comment]
Looks like the issue here is that we're not building the Framework with the `-fembed-bitcode` flag. That's an easy fix to https://github.com/firebase/FirebaseUI-iOS/blob/master/build_database.sh#L39, but it might take me a few days to get things pushed out.

In the meantime, feel free to clone the repo, add the flag, `chmod +x build_database.sh` and run `./build_database.sh` to get a bitcode enabled framework.

**Comment by yacine555** [comment]
Hi, I have the same issue as Toddlee. I cloned the project and added the C FLAG below:
 OTHER_CFLAGS="-fembed-bitcode" \

Though now I am getting the below compilation error:

** BUILD FAILED **


The following build commands failed:
	Libtool target/Intermediates/FirebaseUI.build/Release-iphoneos/Database.build/Objects-normal/armv7s/libDatabase.a normal armv7s
	Libtool target/Intermediates/FirebaseUI.build/Release-iphoneos/Database.build/Objects-normal/arm64/libDatabase.a normal arm64
	Libtool target/Intermediates/FirebaseUI.build/Release-iphoneos/Database.build/Objects-normal/armv7/libDatabase.a normal armv7
(3 failures)

Any ideas why?

Thanks a lot

**Comment by kressm** [comment]
@mcdonamp Does that mean we will have to do a manual install outside of cocoapods? Could you explain the steps as I'm not able to compile my app and turning bitcode off isn't an option. @toddlee what did you do to get it resolved? Thanks!

**Comment by toddlee** [comment]
I think I cloned the repository, added the all files (*.m & *.h) directly to my project.. it isn't ideal but for now, it's a quick workaround.

**Comment by mcdonamp** [comment]
Fun times with bugs... Looks like there's an issue with XCode 7.3 which doesn't let you build with bitcode enabled from a script (which is what we do), even if you have bitcode enabled in your project (which we do). See http://stackoverflow.com/questions/36184930/xcodebuild-7-3-cant-enable-bitcode for more details.

Trying to work around that (I may install XCode 8 if I'm feeling like living on the edge), otherwise I'll change the build script to use their "recommended" hacks.

**Comment by kressm** [comment]
@mcdonamp Is there nothing I can do for a workaround until you make the changes to the script available through cocoapods? I don't see how I can modify the script. Any help would be great as I really need a workaround ASAP. Thanks!

**Comment by mcdonamp** [comment]
@kressm it's all open source code, so you're welcome to use it locally and play around with it to try and make it work--you're not blocked on me doing anything. I'm looking at adding an `unset TOOLCHAIN` to the build script, but I haven't been able to verify if that solves the problem yet.

**Comment by aldo-jlaurenstin** [comment]
Hi guys any news on the bug? I'm running into an issue with Firebase where I can't have the build my app for Distribution with the Push Notification working (FCM). But when I run directly from XCode to the device, I receive the push notification properly.

**Comment by seanpc9** [comment]
Has this bug been fixed? I still can't build my app for submission...

**Comment by mcdonamp** [comment]
@morganchen12 I think this should be solved in your build process. Can you make sure we're adding bitcode support here (should be in the scheme we build the library from, though we may need to add it in the build script).

**Comment by mlake** [comment]
Any ETA on when we might expect a fix for this?

**Comment by chadpav** [comment]
+1 this issue

For now, it was ok for me to disable bit code in my project Build Settings (enable Bitcode == NO) to unblock.

**Comment by morganchen12** [comment]
I'm working on this and will hopefully get it done by early next week.

**Comment by morganchen12** [comment]
This should be fixed in the latest release. If it's not, reopen and I'll take a look again. 👍

**Comment by seanpc9** [comment]
Still got this error:

`bitcode bundle could not be generated because 'Pods/FirebaseUI/FirebaseUIFrameworks/Auth/Frameworks/FirebaseAuthUI.framework/FirebaseAuthUI(FIRAuthPickerViewController.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64`

This was after upgrading to version 0.5.

**Comment by morganchen12** [comment]
I'll take a look.

**Comment by morganchen12** [comment]
@seanpc9 this should be fixed _for real_ in the 0.5.1 release.

**Comment by seanpc9** [comment]
@morganchen12 it does indeed work, thank you!

**Comment by morganchen12** [comment]
I broke this when fixing the whole library not working, gonna try to address this again soon

**Comment by LeChatNoir69** [comment]
ame issue for me. Just made a pod update.
=> Installing FirebaseUI 0.5.4 (was 0.4.0)

But now, got this error : 
[FIRAuthUI authUI]
=> No known class method for selector authUI...
:(

**Comment by LeChatNoir69** [comment]
Ok. Fixed.
authUI is now defaultAuthUI
signInProviders property is now just providers

Compile ok. And I can archive for release now :)

**Comment by LeChatNoir69** [comment]
Aouch... Not finished :(
After submitting, I've got this message from ITC : 
 While processing your iOS app, XXX, errors occurred in the app thinning process, and your app couldn’t be thinned. If your app contains bitcode, bitcode processing may have failed. Because of these errors, this build of your app will not be able to be submitted for review or placed on the App Store.

I'll have a deeper look but seems to be a probleme again :(

**Comment by LeChatNoir69** [comment]
All right. I can publish my app. Just have to upgrade to last XCode.
So now, let's cross fingers :)

**Comment by morganchen12** [comment]
This should be fixed on our end. Reopen if you run into issues again.
