### ISSUE TITLE
Unable to build Example App

### ISSUE THREAD

**Issue by grantkemp** [firebase/FirebaseUI-iOS#67]
I tried to build example app - but I got the following error: 
#import "FirebaseUI/FirebaseTableViewDataSource.h" not found. 
Has this been deprecated?

**Comment by albertodebortoli** [comment]
Same here.

**Comment by grantkemp** [comment]
@albertodebortoli  Yay - its not just me... Tell Marco hi from me. Nice to see the work you guys are doing with JE App

**Comment by mcdonamp** [comment]
It'll be `FirebaseDatabaseUI/...`. We're working on updating the app with the new Authentication, so we'll clean this up along the way. Sorry about the brokenness :/

**Comment by grantkemp** [comment]
@mcdonamp if you can find a way to make the demo app a single page app( or at most 2 vcs)  - it would make it really simple to understand. If you can't demo in a single page app- its not worth demoing...

**Comment by mcdonamp** [comment]
I think it is a single VC, right? Is the issue that there are things spread across multiple files (there's a custom datasource, custom cells, etc.)?

**Comment by dakeshi** [comment]
@mcdonamp, In addition to filename issue,  FirebaseUIChat example has more issue about podspec.
When I install the FirebaseUIChat with the following instructions in README, FirebaseUI pod is not existed in the workspace. 

> cd FirebaseUI-iOS/examples/FirebaseUIChat
pod install
open FirebaseUIChat.xcworkspace

If I edit Podfile with `pod 'FirebaseUI'` instead of `pod 'FirebaseUI', :path => "../../FirebaseUI.podspec"`,
I can find out FirebaseUI in the workspace.

I think that there are some problem in FirebaseUI.podspec, especially the below line:

>   s.source       = { :http => 'https://dl.google.com/firebase/firebaseui/ios/0_4_0/FirebaseUIFrameworks.zip' }

So, I edit podspec with this:
>   s.source       = { :git => 'https://github.com/firebase/FirebaseUI-iOS.git', :tag => s.version }

and try to `pod install` with original Podfile configuration 
(`pod 'FirebaseUI', :path => "../../FirebaseUI.podspec"`)

The result is...it's success.

I think that use `pod 'FirebaseUI'` in example/Podfile is more clear for many users who want to know how to work FirebaseUI.

**Comment by dakeshi** [comment]
I'll try to fix this issues with new authentication. Should I keep the structure of the example source? I just show sign in button in the FirstViewController and call authViewController when clicked the button.

**Comment by apwelsh** [comment]
Has this not bee fixed yet?  How do I get around this?  I am rather new to Swift and Xcode these days, as I have not used it in a few years, and have only used the playground for Swift.  I need a working example to see how to use FirebaseUI with Swift.   Please provide some guidance.

**Comment by salqadri** [comment]
I see this issue as well.

**Comment by wagyu298** [comment]
Hi, I got same error with cocoapods-1.0.1.

**Comment by morganchen12** [comment]
@apwelsh and others: can you take a look at the newly added Swift samples in `samples/swift` and see if they resolve your issues? There's only database stuff there now, the Auth sample is currently being reviewed (#95).

**Comment by apwelsh** [comment]
It is the auth stuff i am looming for.  That is what is of the most concern to me.  I will look at the examples for data access to see if it makes sense and how different it would be compared to the standard Firebase api.

Armand
--Sent from iPhone

**Comment by morganchen12** [comment]
#95 has been merged, so I'm gonna close this. Re-open if you're still having trouble.
