### ISSUE TITLE
Unable to install FirebaseUI in the example

### ISSUE THREAD

**Issue by dakeshi** [firebase/FirebaseUI-iOS#75]
In addition to filename issue(#67),  FirebaseUIChat example has more issues about Podfile.
When I install the FirebaseUIChat with the following instructions in README, FirebaseUI pod is not existed in the workspace. But I get the installation success message from pod install.

- intallation
> cd FirebaseUI-iOS/examples/FirebaseUIChat
pod install
open FirebaseUIChat.xcworkspace

- pod install messages
> Installing Bolts (1.7.0)
Installing FBSDKCoreKit (4.13.1)
Installing FBSDKLoginKit (4.13.1)
Installing Firebase (3.2.1)
Installing FirebaseAnalytics (3.2.0)
Installing FirebaseAuth (3.0.2)
Installing FirebaseDatabase (3.0.1)
Installing FirebaseInstanceID (1.0.6)
**Installing FirebaseUI (0.4.0)**
Installing GoogleAppUtilities (1.1.1)
Installing GoogleAuthUtilities (2.0.1)
Installing GoogleInterchangeUtilities (1.2.1)
Installing GoogleNetworkingUtilities (1.2.1)
Installing GoogleSignIn (4.0.0)
Installing GoogleSymbolUtilities (1.1.1)
Installing GoogleUtilities (1.3.1)
Pod installation complete! There is 1 dependency from the Podfile and 16 total
pods installed.

If I edit Podfile with `pod 'FirebaseUI'` instead of `pod 'FirebaseUI', :path => "../../FirebaseUI.podspec"`,
FirebaseUI is successfully installed in the workspace. 

Is there some problem in FirebaseUI.podspec?

**Comment by mcdonamp** [comment]
The goal behind using the `../../FirebaseUI.podspec` is that this allows the developer to use a local podspec for development work--they can change the FirebaseUI code and then immediately test it in the sample app. This is super handy for development, but maybe not as great for an example app for developers not interested in working on the library (for that, I'd recommend checking out [FriendlyPix](https://github.com/firebase/FriendlyPix), one of our sample apps). This may be totally borked anyways since we're always pulling from a zip file, rather than a git repo.

Or it's an issue with how CocoaPods 1.0.0 handles local paths, or we've moved the path around.

**Comment by dakeshi** [comment]
Thank you for your feedback. @mcdonamp
I agree with an advantage of local podspec 😄  and
was not worried about experienced users. 

How was the beginner? They may want to see how works FirebaseUI and try to install FirebaseUI example with instructions. If they can not get expected results, they will leave the project. 
And they will talk about the quality of the firebase or google brand.(In the worst case)

I test podspec with git repo, get the same result. FirebaseUI pod has not in the workspace.
 >   s.source       = { :git => 'https://github.com/firebase/FirebaseUI-iOS.git', :tag => s.version }

As you mentioned, it could be CocoaPods 1.0.0 issues.

**Comment by mcdonamp** [comment]
Totally agree that nailing the getting started experience is important--though I wouldn't blame you for not thinking so, given the state of our open source iOS repos at the moment. The short answer is that we experienced a major version bump in our client (2.x -> 3.x), in CocoaPods (0.39 -> 1.0), in iOS (9 -> 10), and Swift (2.2 -> 2.3, 3.0), all within a month or so, and we're still having trouble adjusting to the matrix of problems that seem to have come from it.

I'm happy to accept a PR fixing this issue by any reasonable means. The root cause of all our CocoaPods issues is that we support iOS 7 (and thus, we ship static libs wrapped in Frameworks), while Apple (and CocoaPods by extension), really couldn't care less about supporting old OS's or framework developers. As further proof, I don't believe XCode 8 ships with iOS 7 support :)

**Comment by dakeshi** [comment]
Perfect thanks so much for detailed your answer. 👍 
 
> we're still having trouble adjusting to the matrix of problems that seem to have come from it.
That's why we need contributors. 😄 

>I'm happy to accept a PR fixing this issue by any reasonable means.
I'll keep try to find out an appropriate solution.

**Comment by dakeshi** [comment]
I'll make PR #77 to fix this issue. Welcome to your reviews.

**Comment by hmistry** [comment]
I'm having same issue. I tried the solution and many other path variations by editing the path for FirebaseUI in the `Podfile` and in the .h file where the error is but no luck. The error I get is on line 17 in `MessageDataSource.h` file and the error is "FirebaseUI/FirebaseTableViewDataSource.h file not found". Tried with pod v1.0.1 and v1.1.0.beta.

Any suggestions to get this working?

**Comment by dakeshi** [comment]
@hmistry, Firebase team have tried to solve this issue.
So, we have to wait until their new version(https://github.com/firebase/FirebaseUI-iOS/pull/89) is completed.

**Comment by MMujtabaRoohani** [comment]
I was having the same issue, firstly I changed podfile from 
`pod 'FirebaseUI', :path => "../../FirebaseUI.podspec"`
to 
`pod 'FirebaseUI', '~> 0.4'`
and then changed imports of FirebaseUI to FirebaseDatabaseUI and that worked.

**Comment by morganchen12** [comment]
#89 is merged, objc samples coming soon™. Hope it helps, and thanks for your patience 😅

**Comment by dakeshi** [comment]
#89, #95 is merged for the new swift example.
