### ISSUE TITLE
Customize the generated viewController FIRAuthUI.authUI().authViewController() 

### ISSUE THREAD

**Issue by jerydarkside** [firebase/FirebaseUI-iOS#87]
### Details:
  1.  Swift:
  2. iOS 9:
  3. Firebase UI Version: 0.4.0

### Explanation of your issue
There is no easy way to customize the first view controller of FIRAuthUI.authUI()
If I try to add a background like that:

```
 let authUI = FIRAuthUI.authUI()
 authUI?.delegate = self
        
 let googleAuthUI = FIRGoogleAuthUI(clientID: ".......")
 authUI?.signInProviders = [googleAuthUI!]
        
let authViewController = authUI?.authViewController()
let backgroundImageView = UIImageView(image: UIImage(named: "background"))
authViewController?.view.insertSubview(backgroundImageView, atIndex: 0)
        
self.presentViewController(authViewController!, animated: true, completion: nil)
```
my background is hidden behind a tableview generated by authViewController.

![capture d ecran 2016-07-19 a 01 14 06](https://cloud.githubusercontent.com/assets/2154251/16933509/3f7d2194-4d4e-11e6-8bdc-69c92e26521b.png)

In one of Firebase conf (https://youtu.be/0ucjYG_JrEE?t=39m14s), they talk about subclassing in iOS to customize the generated view controllers. But I can't find in the SDK where to do that.

I've been searching for quite a while. Can you help me?

Thank you

(_If there is a more elegant way, I would like to avoid to loop through all viewController subviews to detect the tableView and make its background transparent_)

**Comment by chaogoog** [comment]
`FIRAuthUI` has a delegate method called `authPickerViewControllerForAuthUI:`. You can implement that method to provide an instance of your subclass of `FIRAuthPickerViewController`. It should be much easier to customize the first screen in the subclass.

Note that `authUI?.authViewController()` itself is not the first screen. It's the `UINavigationController` that wraps all view controllers rather.

**Comment by jerydarkside** [comment]
Ah yes! Thank you! That's exactly what I've been searching!

**Comment by shugums** [comment]
Could you possibly explain how to do this in more detail?  I created a subclass of`FIRAuthPickerViewController `.  I am just not sure how to provide `FIRAuthUI` with an instance of the subclass by implementing the delegate method `authPickerViewControllerForAuthUI ` (taken from Auth Documentation).  Essentially, where do I place the below provided code?  Thanks!
```
func authPickerViewControllerForAuthUI(authUI: FIRAuthUI) -> FIRAuthPickerViewController {
   return  CustomAuthPickerViewController(authUI: authUI)
}
```

**Comment by morganchen12** [comment]
That code goes on any object conforming to `FIRAuthUIDelegate`. Then, before instantiating your auth flow, set the `FIRAuthUI` delegate to your delegate object.

`delegate` is a bit of a misnomer, later on we should rename this to `dataSource` and split this method out of the delegate protocol.

**Comment by shugums** [comment]
Follow up question (new to swift/xcode):

The object you are referencing that should conform to the `FIRAuthUIDelegate` should be the subclassed `FIRAuthPickerViewController` controller? And if that’s true, then what are the functions that need to be passed in a delegate object for this controller to that it can be set to the `FIRAuthUI`? If we are loading this file as the initial root controller in the app delegate do we set that equal to the `authUI?.authViewController()`?  Should it take the custom class that we have created or should we call the reference to the name of the custom class?

Thanks in advance!

**Comment by morganchen12** [comment]
Any type can conform to `FIRAuthUIDelegate`. To set the delegate on the FIRAuthUI instance, assuming you're using the default FIRAuthUI instance:

```swift
let authDelegate = /* instantiate your auth delegate object */
FIRAuthUI.defaultAuthUI().delegate = authDelegate
```

Which type in particular you want your delegate to be is up to you.

**Comment by yorgosg** [comment]
Hello, one more issue related to the custom authviewcontroller:

I have created a subclass of FIRAuthPickerViewController which is presented by the delegate class and is shown correctly, but ever since I used the subclass to customize the UI of the authViewController, the didSignInWithUser method is no longer called upon signing in.

I use my app delegate to present the custom view controller. The app delegate is also the authUI delegate I have been using. I have implemented within the app delegate the following code, like suggested:

- (FIRAuthPickerViewController *)authPickerViewControllerForAuthUI:(FIRAuthUI *)authUI {
    return [[MyCustomLoginViewController alloc] initWithAuthUI:authUI];
}

and the app delegate uses the following code to present the view:

FIRAuthUI *authUI = [FIRAuthUI defaultAuthUI];
authUI.delegate = self; // Set the delegate to receive callback.
    
FIRAuthPickerViewController *myCustomLoginViewController = [self authPickerViewControllerForAuthUI:authUI];

 [self presentViewController:myCustomLoginViewController animated:YES completion:nil];

and everything is shown correctly in my custom view. But when I sign in, the didSignInWithUser is no longer being called.

(Also, the Cancel button is missing now that I subclassed the view, but that's not a problem :) )

Any ideas?
