### ISSUE TITLE
Auth podspec should depend on 7.2.0 or higher

### ISSUE THREAD

**Issue by ramunasjurgilas** [firebase/FirebaseUI-iOS#936]
Error: **/MyProject/ios/Pods/FirebaseUI/Auth/FirebaseAuthUI/FUIAuth.m:341:14: No visible @interface for 'FIRAuth' declares the selector 'useEmulatorWithHost:port:'**

IDE: Xcode 12

All pods in my target:
```
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'FirebaseStorageSwift'
```

What is the way to get rid of this error?

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/255732/105915145-06981f80-6038-11eb-86e8-1bec8cca7ab4.png">

**Comment by morganchen12** [comment]
You should update your version of Firebase Auth to [7.2.0](https://firebase.google.com/support/release-notes/ios#version_720_-_december_2_2020) or higher.

**Comment by morganchen12** [comment]
We should probably fix this in the podspec.

**Comment by yo1995** [comment]
FYI: Today (210401) the `FirebaseFirestoreSwift` pod and `Firebase/Auth` pod have different version requirement/dependency on `FirebaseCore`. 

Due to this conflict, I cannot update all pods to the latest version because of the `No visible @interface for 'FIRAuth' declares the selector 'useEmulatorWithHost:port:'` error from the auth pod. 😞 

While waiting for this issue being fixed, I'll stick with the older versions in our `podfile.lock`...

**Comment by paulb777** [comment]
https://github.com/firebase/firebase-ios-sdk/issues/7195 may be relevant
